### ISSUE TITLE
Add fast sync with initial-state on Teku and Windows

### ISSUE THREAD

**Issue by remyroy** [stake-house/eth2-validator-wizard#17]
Request that the user create an Infura ETH2 project for fast sync (in minutes) with the `--initial-state` on Teku. See https://docs.teku.consensys.net/en/latest/HowTo/Get-Started/Checkpoint-Start/

**Comment by ajsutton** [comment]
Worth noting that there's nothing special about Infura here other than the fact that it provides anyone access with just a free account.  The state can be returned via the standard Api from any node or just from any file or URL if you have a state from some other method.

From the standard API it's just `<node-url>/eth/v1/debug/beacon/states/finalized` (e.g `http://localhost:5051/eth/v1/debug/beacon/states/finalized`) and that node-url could be the URL Infura give on their dashboard. I recorded a quick demo of the process: https://www.youtube.com/watch?v=ce9uVRl23zI

**Comment by remyroy** [comment]
Great video. I wonder if the StakeHouse community could provide a public and free specialized endpoint just for that. I wonder how much resources would be needed if that is just a one off per staking machine. Food for thought. In the meantime, we'll go with the path of least resistance which is probably Infura.

**Comment by ajsutton** [comment]
> Great video. I wonder if the StakeHouse community could provide a public and free specialized endpoint just for that. I wonder how much resources would be needed if that is just a one off per staking machine. Food for thought. In the meantime, we'll go with the path of least resistance which is probably Infura.

I'd love to see more distributed infrastructure appear for this kind of thing. Each request is very little impact on the node itself but given each state is about 20Mb if you were serving a lot of people the bandwidth adds up. The standard API I mentioned above gives a state that will change generally every epoch (assuming we're finalising normally) but you don't need it to be that up to date - anything from the last day or so will give you nice fast sync times.  So you could utilise long cache times to reduce the amount of bandwidth needed from the node itself.  You could use something like Bittorrent to distribute the state which would distribute the load more evenly for example.

Not sure exactly how that would fit with StakeHouse but if we can solve the state availability problem I suspect every client will quite quickly implement this snapshot sync because it is just so much better.

**Comment by remyroy** [comment]
Let's say we want to provide this public and free *states only* beacon node endpoint, here is my napkin math for cost estimation. Let's be liberal in overestimating our bandwith usage.

Let's assume that we get the traffic for all the new validators on mainnet twice (on average because they messed up the first time). Let's assume all those validators are using a different machine for each of their key. Let's assume that the month of April 2021 with its 13194 new validators on mainnet is an average that will continue into the future.

We get 13194 * 20 MB * 2 = 528 GB of outbound traffic for the public serving of those states.

Let's assume that a normal beacon node only consume about 1 TB of outbound traffic per month.

We get 1 TB + 528 GB = 1.528 TB of outbound traffic per month.

With that amount it should be easily covered within the free allowance (5 TB) of [a good enough DO droplet for about 130$ USD/month](https://www.digitalocean.com/community/tools/bandwidth?active=%5B%7B%22slug%22%3A%22gd-4vcpu-16gb%22%2C%22type%22%3A%22droplet%22%2C%22hours%22%3A744%2C%22consumption%22%3A1528%2C%22nodes%22%3A1%7D%5D&additional=0) assuming the specs of that droplet (4 dedicated CPUs, 16 GB of RAM, 100 GB NVMe SSD disk) is enough for running a naked beacon node.

This is assuming we can setup a good rate limiting front and control abuses accordingly. DDoS protection would need more investigation.

Let's say we want to also provide this free public service for Pyrmont and Prater and the outbound traffic for testnet states is similar or at least withing the bound of the combined droplets free allowance, we would need 3 of those droplets.

We get 130$ USD/month * 3 = 390$ USD/month = 4680$ USD/year

Even we were to exceed the free outbound allowance for a month, the cost of exceeding outbound traffic is only 10$ USD/TB.

Can we get 4680$ USD/year of funding from the Ethereum community for this? Hell Yeah! This would be a drop in the ocean for ConsenSys 😅

**Comment by remyroy** [comment]
This should be completed with a4b6d82e12b8d4d32309b2775fe686a8230b73a9 .
